#!/bin/sh

# chkconfig: 2345 20 80
# description: iPlant Notification Agent

. /etc/init.d/functions

################################################################################
# Specific script configuration
# Change these as needed to run a specific nodejs program.
################################################################################
RUNUSER=iplant
program=iplant-email
jarfile=iplant-email-1.0.0-SNAPSHOT-standalone.jar
jar=/usr/local/lib/${program}/${jarfile}
conf=/etc/${program}
mainclass=${program}.core

################################################################################

################################################################################
# Generic paths
# None of these should need to be changed to execute a nodejs script unless 
# there is specific configuration that is needed for the script.
################################################################################ 
piddir=/var/run/$program
pidfile=/var/run/$program/$program.pid
lockfile=/var/lock/subsys/$program
logdir=/var/log/$program
RETVAL=0

start () {
    echo -n $"Starting $program: "
    runuser -m -s /bin/bash -l $RUNUSER -c "nohup java -cp .:${conf}:${jar} ${mainclass}" < /dev/null &> ${logdir}/launch.log &
    RETVAL=$?
    echo $! > ${pidfile}

    [ $RETVAL = 0 ] && success && touch ${lockfile}
    [ $RETVAL -ne 0 ] && failure
    echo

    return $RETVAL
}

stop () {
    echo -n $"Stopping $program: "
    killproc -p ${pidfile}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -rf ${lockfile} ${pidfile}
}

restart () {
    echo -n $"Restarting $program: "
    stop
    start
}

showstatus () {
    status -p ${pidfile} ${program}
    RETVAL=$?
}

case "$1" in
    start)
        start
    ;;
    
    stop)
        stop
    ;;
    
    restart)
        restart
    ;;
    
    status)
        showstatus
    ;;
    
    *)
        echo "Usage: $program {start|stop|restart,status}"
        exit 1
    ;;
esac

exit $RETVAL
